default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: cheers_development

test:
  <<: *default
  database: cheers_test

production:
  <<: *default
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
